INSERT INTO ROLES(NAME) VALUES('ROLE_CUSTOMER');

INSERT INTO ROLES(NAME) VALUES('ROLE_USER');

INSERT INTO ROLES(NAME) VALUES('ROLE_ADMIN');

INSERT INTO ESTADO_REPORTE(DESCRIPCION, DESCRIPCION_SEGUNDARIA, COLOR)
    VALUES('Enviado', 'En Espera', '#2DCCFF');

INSERT INTO ESTADO_REPORTE(DESCRIPCION, DESCRIPCION_SEGUNDARIA, COLOR)
    VALUES('Asignado', 'En Revision', '#FFB302');

INSERT INTO ESTADO_REPORTE(DESCRIPCION, DESCRIPCION_SEGUNDARIA, COLOR)
    VALUES('En Proceso', 'Technicians Trabajando', '#FCE83A');

INSERT INTO ESTADO_REPORTE(DESCRIPCION, DESCRIPCION_SEGUNDARIA, COLOR)
    VALUES('Terminado', 'Entregado', '#56F000');

INSERT INTO TECNICO(NOMBRE, APELLIDO, TELEFONO, LATITUD, LONGITUD)
    VALUES('JUAN','MECANICO','809-555-5555', '18.485120556117405', '-69.92053023702806');

INSERT INTO TECNICO(NOMBRE, APELLIDO, TELEFONO, LATITUD, LONGITUD)
    VALUES('JULIO','TECNICO','809-471-5555', '18.48710119592701', '-69.94218301516523');

INSERT INTO TIPO_REPORTE(DESCRIPCION)
    VALUES('Hoyo en Pavimento');

INSERT INTO TIPO_REPORTE(DESCRIPCION)
    VALUES('Otro');