CREATE TABLE SOLICITUD_REGISTRO (
    TELEFONO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(120) NOT NULL,
    APELLIDO VARCHAR(120) NOT NULL,
    CORREO VARCHAR(120),
    OTP VARCHAR(10),
    PRIMARY KEY(TELEFONO)
);

CREATE TABLE USERS (
    USERNAME VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(120) NOT NULL,
    APELLIDO VARCHAR(120) NOT NULL,
    PASSWORD VARCHAR(120) NOT NULL,
    CORREO VARCHAR(120),
    PRIMARY KEY(USERNAME)
);

CREATE TABLE ROLES (
    ID IDENTITY NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE USER_ROLES (
    USER_ID VARCHAR(50) NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    PRIMARY KEY(USER_ID, ROLE_ID)
);

CREATE TABLE REPORTE (
    ID IDENTITY NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    TIPO_REPORTE VARCHAR(120) NOT NULL,
    LONGITUD VARCHAR(250) NOT NULL,
    LATITUD VARCHAR(250) NOT NULL,
    NOTAS VARCHAR(400),
    NOMBRE VARCHAR(120) NOT NULL,
    APELLIDO VARCHAR(120) NOT NULL,
    CORREO VARCHAR(80),
    TELEFONO VARCHAR(50) NOT NULL,
    FECHA_CREACION TIMESTAMP NOT NULL,
    FECHA_ULTIMO_ESTADO TIMESTAMP,
    ID_PROYECTO INTEGER,
    ESTADO INTEGER NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE HISTORICO_REPORTE (
    ID IDENTITY NOT NULL,
    ID_REPORTE INTEGER NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    FECHA_CIERRE TIMESTAMP NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE ESTADO_REPORTE (
    ID IDENTITY NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    DESCRIPCION_SEGUNDARIA VARCHAR(100) NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE TIPO_REPORTE (
    ID IDENTITY NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE PROYECTO (
    ID IDENTITY NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    NOTAS VARCHAR(400),
    ESTIMADO_MESES INTEGER NOT NULL,
    ENCARGADO VARCHAR(250) NOT NULL,
    FECHA_CREACION TIMESTAMP NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE FOTOS_REPORTE (
    ID IDENTITY NOT NULL,
    ID_REPORTE INTEGER NOT NULL,
    URL_FOTO VARCHAR(250) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE ASISTENCIA (
    ID IDENTITY NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NOT NULL,
    TIPO_SITUACION  VARCHAR(100) NOT NULL,
    SITUACION  VARCHAR(2000),
    PLACA      VARCHAR(20) NOT NULL,
    TIPO_VEHICULO  VARCHAR(50),
    MARCA       VARCHAR(50),
    MODELO       VARCHAR(50),
    COLOR       VARCHAR(20),
    FECHA_LLAMADA TIMESTAMP,
    FECHA_ASISTENCIA TIMESTAMP,
    URL_IMAGEN_FIRMA VARCHAR(100),
    LATITUD     VARCHAR(50) NOT NULL,
    LONGITUD    VARCHAR(50) NOT NULL,
    ID_TECNICO     INTEGER,
    NOTAS_TECNICO  VARCHAR(2000),
    ESTADO      VARCHAR(20),
    PRIMARY KEY(ID)
);

CREATE TABLE TECNICO(
    ID IDENTITY NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(50)  NOT NULL,
    LATITUD     VARCHAR(50) NOT NULL,
    LONGITUD    VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE SECUENCIA_FOTO (
    ID IDENTITY NOT NULL,
    PRIMARY KEY(ID)
);